default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: servewise_market_development

test:
  <<: *default
  database: servewise_market_test

production:
  <<: *default
  database: servewise_market_production
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
